# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SCRV.ui'
#
# Created: Thu Jul 21 16:22:26 2011
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SCRV(object):
    def setupUi(self, SCRV):
        SCRV.setObjectName("SCRV")
        SCRV.resize(528, 642)
        self.SCRVName = QtGui.QLabel(SCRV)
        self.SCRVName.setGeometry(QtCore.QRect(160, 10, 361, 71))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setWeight(75)
        font.setItalic(True)
        font.setUnderline(False)
        font.setBold(True)
        self.SCRVName.setFont(font)
        self.SCRVName.setObjectName("SCRVName")
        self.AlbaLogo = QtGui.QLabel(SCRV)
        self.AlbaLogo.setGeometry(QtCore.QRect(10, 10, 126, 71))
        self.AlbaLogo.setPixmap(QtGui.QPixmap(":/ALBA_Logo.png"))
        self.AlbaLogo.setObjectName("AlbaLogo")
        self.upperJawLabel = QtGui.QLabel(SCRV)
        self.upperJawLabel.setGeometry(QtCore.QRect(10, 90, 154, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.upperJawLabel.setFont(font)
        self.upperJawLabel.setObjectName("upperJawLabel")
        self.lowerJawLabel = QtGui.QLabel(SCRV)
        self.lowerJawLabel.setGeometry(QtCore.QRect(10, 600, 152, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lowerJawLabel.setFont(font)
        self.lowerJawLabel.setObjectName("lowerJawLabel")
        self.abort = QtGui.QPushButton(SCRV)
        self.abort.setGeometry(QtCore.QRect(330, 80, 141, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abort.sizePolicy().hasHeightForWidth())
        self.abort.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.abort.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.abort.setFont(font)
        self.abort.setObjectName("abort")
        self.upperJaw = QtGui.QGroupBox(SCRV)
        self.upperJaw.setGeometry(QtCore.QRect(10, 140, 190, 144))
        self.upperJaw.setObjectName("upperJaw")
        self.vboxlayout = QtGui.QVBoxLayout(self.upperJaw)
        self.vboxlayout.setSpacing(0)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.upperStepper = widget.TauGroupBox(self.upperJaw)
        self.upperStepper.setFlat(True)
        self.upperStepper.setProperty("showText", QtCore.QVariant(False))
        self.upperStepper.setObjectName("upperStepper")
        self.gridlayout = QtGui.QGridLayout(self.upperStepper)
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(0)
        self.gridlayout.setObjectName("gridlayout")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.upperLabelState = widget.TauValueLabel(self.upperStepper)
        self.upperLabelState.setMinimumSize(QtCore.QSize(50, 22))
        self.upperLabelState.setFrameShape(QtGui.QFrame.NoFrame)
        self.upperLabelState.setFrameShadow(QtGui.QFrame.Plain)
        self.upperLabelState.setProperty("showQuality", QtCore.QVariant(False))
        self.upperLabelState.setProperty("useParentModel", QtCore.QVariant(True))
        self.upperLabelState.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/State", None, QtGui.QApplication.UnicodeUTF8)))
        self.upperLabelState.setObjectName("upperLabelState")
        self.hboxlayout.addWidget(self.upperLabelState)
        self.upperLedState = widget.TauStateLed(self.upperStepper)
        self.upperLedState.setProperty("useParentModel", QtCore.QVariant(True))
        self.upperLedState.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/State", None, QtGui.QApplication.UnicodeUTF8)))
        self.upperLedState.setObjectName("upperLedState")
        self.hboxlayout.addWidget(self.upperLedState)
        spacerItem = QtGui.QSpacerItem(150, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.upperLimitN = widget.TauLimitSwitch(self.upperStepper)
        self.upperLimitN.setProperty("useParentModel", QtCore.QVariant(True))
        self.upperLimitN.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Limit_switches", None, QtGui.QApplication.UnicodeUTF8)))
        self.upperLimitN.setProperty("boolIndex", QtCore.QVariant(2))
        self.upperLimitN.setObjectName("upperLimitN")
        self.hboxlayout.addWidget(self.upperLimitN)
        self.upperLimitLabel = QtGui.QLabel(self.upperStepper)
        self.upperLimitLabel.setObjectName("upperLimitLabel")
        self.hboxlayout.addWidget(self.upperLimitLabel)
        self.upperLimitP = widget.TauLimitSwitch(self.upperStepper)
        self.upperLimitP.setProperty("useParentModel", QtCore.QVariant(True))
        self.upperLimitP.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Limit_switches", None, QtGui.QApplication.UnicodeUTF8)))
        self.upperLimitP.setProperty("boolIndex", QtCore.QVariant(1))
        self.upperLimitP.setObjectName("upperLimitP")
        self.hboxlayout.addWidget(self.upperLimitP)
        self.gridlayout.addLayout(self.hboxlayout, 0, 0, 1, 1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setSpacing(2)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.upperMoveIn = QtGui.QPushButton(self.upperStepper)
        self.upperMoveIn.setObjectName("upperMoveIn")
        self.hboxlayout1.addWidget(self.upperMoveIn)
        self.upperInValue = QtGui.QDoubleSpinBox(self.upperStepper)
        self.upperInValue.setDecimals(3)
        self.upperInValue.setMinimum(0.005)
        self.upperInValue.setMaximum(20.0)
        self.upperInValue.setSingleStep(0.001)
        self.upperInValue.setProperty("value", QtCore.QVariant(1.0))
        self.upperInValue.setObjectName("upperInValue")
        self.hboxlayout1.addWidget(self.upperInValue)
        self.upperInStepperUnits = widget.TauConfigLabel(self.upperStepper)
        self.upperInStepperUnits.setMinimumSize(QtCore.QSize(35, 24))
        self.upperInStepperUnits.setMaximumSize(QtCore.QSize(35, 24))
        self.upperInStepperUnits.setProperty("useParentModel", QtCore.QVariant(True))
        self.upperInStepperUnits.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Position?configuration=unit", None, QtGui.QApplication.UnicodeUTF8)))
        self.upperInStepperUnits.setObjectName("upperInStepperUnits")
        self.hboxlayout1.addWidget(self.upperInStepperUnits)
        self.gridlayout.addLayout(self.hboxlayout1, 1, 0, 1, 1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setSpacing(2)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.upperMoveOut = QtGui.QPushButton(self.upperStepper)
        self.upperMoveOut.setObjectName("upperMoveOut")
        self.hboxlayout2.addWidget(self.upperMoveOut)
        self.upperOutValue = QtGui.QDoubleSpinBox(self.upperStepper)
        self.upperOutValue.setDecimals(3)
        self.upperOutValue.setMinimum(0.005)
        self.upperOutValue.setMaximum(20.0)
        self.upperOutValue.setSingleStep(0.001)
        self.upperOutValue.setProperty("value", QtCore.QVariant(1.0))
        self.upperOutValue.setObjectName("upperOutValue")
        self.hboxlayout2.addWidget(self.upperOutValue)
        self.upperOutStepperUnits = widget.TauConfigLabel(self.upperStepper)
        self.upperOutStepperUnits.setMinimumSize(QtCore.QSize(35, 24))
        self.upperOutStepperUnits.setMaximumSize(QtCore.QSize(35, 24))
        self.upperOutStepperUnits.setProperty("useParentModel", QtCore.QVariant(True))
        self.upperOutStepperUnits.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Position?configuration=unit", None, QtGui.QApplication.UnicodeUTF8)))
        self.upperOutStepperUnits.setObjectName("upperOutStepperUnits")
        self.hboxlayout2.addWidget(self.upperOutStepperUnits)
        self.gridlayout.addLayout(self.hboxlayout2, 2, 0, 1, 1)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setSpacing(2)
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.upperMoveAbs = QtGui.QPushButton(self.upperStepper)
        self.upperMoveAbs.setObjectName("upperMoveAbs")
        self.hboxlayout3.addWidget(self.upperMoveAbs)
        self.upperAbsValue = QtGui.QDoubleSpinBox(self.upperStepper)
        self.upperAbsValue.setDecimals(3)
        self.upperAbsValue.setMaximum(20.0)
        self.upperAbsValue.setSingleStep(0.001)
        self.upperAbsValue.setProperty("value", QtCore.QVariant(1.0))
        self.upperAbsValue.setObjectName("upperAbsValue")
        self.hboxlayout3.addWidget(self.upperAbsValue)
        self.upperAbsStepperUnits = widget.TauConfigLabel(self.upperStepper)
        self.upperAbsStepperUnits.setMinimumSize(QtCore.QSize(35, 24))
        self.upperAbsStepperUnits.setMaximumSize(QtCore.QSize(35, 24))
        self.upperAbsStepperUnits.setProperty("useParentModel", QtCore.QVariant(True))
        self.upperAbsStepperUnits.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Position?configuration=unit", None, QtGui.QApplication.UnicodeUTF8)))
        self.upperAbsStepperUnits.setObjectName("upperAbsStepperUnits")
        self.hboxlayout3.addWidget(self.upperAbsStepperUnits)
        self.gridlayout.addLayout(self.hboxlayout3, 3, 0, 1, 1)
        self.vboxlayout.addWidget(self.upperStepper)
        self.upperEnc = widget.TauGroupBox(self.upperJaw)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upperEnc.sizePolicy().hasHeightForWidth())
        self.upperEnc.setSizePolicy(sizePolicy)
        self.upperEnc.setFlat(True)
        self.upperEnc.setProperty("showText", QtCore.QVariant(False))
        self.upperEnc.setObjectName("upperEnc")
        self.gridlayout1 = QtGui.QGridLayout(self.upperEnc)
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setHorizontalSpacing(4)
        self.gridlayout1.setVerticalSpacing(0)
        self.gridlayout1.setObjectName("gridlayout1")
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.upperEncLabel = QtGui.QLabel(self.upperEnc)
        self.upperEncLabel.setObjectName("upperEncLabel")
        self.hboxlayout4.addWidget(self.upperEncLabel)
        self.upperEncRead = widget.TauValueLabel(self.upperEnc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upperEncRead.sizePolicy().hasHeightForWidth())
        self.upperEncRead.setSizePolicy(sizePolicy)
        self.upperEncRead.setProperty("useParentModel", QtCore.QVariant(True))
        self.upperEncRead.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Position", None, QtGui.QApplication.UnicodeUTF8)))
        self.upperEncRead.setObjectName("upperEncRead")
        self.hboxlayout4.addWidget(self.upperEncRead)
        self.upperEncUnits = widget.TauConfigLabel(self.upperEnc)
        self.upperEncUnits.setMinimumSize(QtCore.QSize(35, 24))
        self.upperEncUnits.setMaximumSize(QtCore.QSize(35, 24))
        self.upperEncUnits.setProperty("useParentModel", QtCore.QVariant(True))
        self.upperEncUnits.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Position?configuration=unit", None, QtGui.QApplication.UnicodeUTF8)))
        self.upperEncUnits.setObjectName("upperEncUnits")
        self.hboxlayout4.addWidget(self.upperEncUnits)
        self.gridlayout1.addLayout(self.hboxlayout4, 0, 0, 1, 1)
        self.vboxlayout.addWidget(self.upperEnc)
        self.lowerJaw = QtGui.QGroupBox(SCRV)
        self.lowerJaw.setGeometry(QtCore.QRect(10, 450, 190, 144))
        self.lowerJaw.setObjectName("lowerJaw")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.lowerJaw)
        self.vboxlayout1.setSpacing(0)
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.lowerStepper = widget.TauGroupBox(self.lowerJaw)
        self.lowerStepper.setFlat(True)
        self.lowerStepper.setProperty("showText", QtCore.QVariant(False))
        self.lowerStepper.setObjectName("lowerStepper")
        self.gridlayout2 = QtGui.QGridLayout(self.lowerStepper)
        self.gridlayout2.setMargin(0)
        self.gridlayout2.setSpacing(0)
        self.gridlayout2.setObjectName("gridlayout2")
        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.lowerLabelState = widget.TauValueLabel(self.lowerStepper)
        self.lowerLabelState.setMinimumSize(QtCore.QSize(50, 22))
        self.lowerLabelState.setFrameShape(QtGui.QFrame.NoFrame)
        self.lowerLabelState.setFrameShadow(QtGui.QFrame.Plain)
        self.lowerLabelState.setProperty("showQuality", QtCore.QVariant(False))
        self.lowerLabelState.setProperty("useParentModel", QtCore.QVariant(True))
        self.lowerLabelState.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/State", None, QtGui.QApplication.UnicodeUTF8)))
        self.lowerLabelState.setObjectName("lowerLabelState")
        self.hboxlayout5.addWidget(self.lowerLabelState)
        self.lowerLedState = widget.TauStateLed(self.lowerStepper)
        self.lowerLedState.setProperty("useParentModel", QtCore.QVariant(True))
        self.lowerLedState.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/State", None, QtGui.QApplication.UnicodeUTF8)))
        self.lowerLedState.setObjectName("lowerLedState")
        self.hboxlayout5.addWidget(self.lowerLedState)
        spacerItem1 = QtGui.QSpacerItem(150, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout5.addItem(spacerItem1)
        self.lowerLimitN = widget.TauLimitSwitch(self.lowerStepper)
        self.lowerLimitN.setProperty("useParentModel", QtCore.QVariant(True))
        self.lowerLimitN.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Limit_switches", None, QtGui.QApplication.UnicodeUTF8)))
        self.lowerLimitN.setProperty("boolIndex", QtCore.QVariant(2))
        self.lowerLimitN.setObjectName("lowerLimitN")
        self.hboxlayout5.addWidget(self.lowerLimitN)
        self.lowerLimitLabel = QtGui.QLabel(self.lowerStepper)
        self.lowerLimitLabel.setObjectName("lowerLimitLabel")
        self.hboxlayout5.addWidget(self.lowerLimitLabel)
        self.lowerLimitP = widget.TauLimitSwitch(self.lowerStepper)
        self.lowerLimitP.setProperty("useParentModel", QtCore.QVariant(True))
        self.lowerLimitP.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Limit_switches", None, QtGui.QApplication.UnicodeUTF8)))
        self.lowerLimitP.setProperty("boolIndex", QtCore.QVariant(1))
        self.lowerLimitP.setObjectName("lowerLimitP")
        self.hboxlayout5.addWidget(self.lowerLimitP)
        self.gridlayout2.addLayout(self.hboxlayout5, 0, 0, 1, 1)
        self.hboxlayout6 = QtGui.QHBoxLayout()
        self.hboxlayout6.setSpacing(1)
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.lowerMoveIn = QtGui.QPushButton(self.lowerStepper)
        self.lowerMoveIn.setObjectName("lowerMoveIn")
        self.hboxlayout6.addWidget(self.lowerMoveIn)
        self.lowerInValue = QtGui.QDoubleSpinBox(self.lowerStepper)
        self.lowerInValue.setDecimals(3)
        self.lowerInValue.setMinimum(0.005)
        self.lowerInValue.setMaximum(20.0)
        self.lowerInValue.setSingleStep(0.001)
        self.lowerInValue.setProperty("value", QtCore.QVariant(1.0))
        self.lowerInValue.setObjectName("lowerInValue")
        self.hboxlayout6.addWidget(self.lowerInValue)
        self.lowerInStepperUnits = widget.TauConfigLabel(self.lowerStepper)
        self.lowerInStepperUnits.setMinimumSize(QtCore.QSize(35, 24))
        self.lowerInStepperUnits.setMaximumSize(QtCore.QSize(35, 24))
        self.lowerInStepperUnits.setProperty("useParentModel", QtCore.QVariant(True))
        self.lowerInStepperUnits.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Position?configuration=unit", None, QtGui.QApplication.UnicodeUTF8)))
        self.lowerInStepperUnits.setObjectName("lowerInStepperUnits")
        self.hboxlayout6.addWidget(self.lowerInStepperUnits)
        self.gridlayout2.addLayout(self.hboxlayout6, 1, 0, 1, 1)
        self.hboxlayout7 = QtGui.QHBoxLayout()
        self.hboxlayout7.setSpacing(1)
        self.hboxlayout7.setObjectName("hboxlayout7")
        self.lowerMoveOut = QtGui.QPushButton(self.lowerStepper)
        self.lowerMoveOut.setObjectName("lowerMoveOut")
        self.hboxlayout7.addWidget(self.lowerMoveOut)
        self.lowerOutValue = QtGui.QDoubleSpinBox(self.lowerStepper)
        self.lowerOutValue.setDecimals(3)
        self.lowerOutValue.setMinimum(0.005)
        self.lowerOutValue.setMaximum(20.0)
        self.lowerOutValue.setSingleStep(0.001)
        self.lowerOutValue.setProperty("value", QtCore.QVariant(1.0))
        self.lowerOutValue.setObjectName("lowerOutValue")
        self.hboxlayout7.addWidget(self.lowerOutValue)
        self.lowerOutStepperUnits = widget.TauConfigLabel(self.lowerStepper)
        self.lowerOutStepperUnits.setMinimumSize(QtCore.QSize(35, 24))
        self.lowerOutStepperUnits.setMaximumSize(QtCore.QSize(35, 24))
        self.lowerOutStepperUnits.setProperty("useParentModel", QtCore.QVariant(True))
        self.lowerOutStepperUnits.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Position?configuration=unit", None, QtGui.QApplication.UnicodeUTF8)))
        self.lowerOutStepperUnits.setObjectName("lowerOutStepperUnits")
        self.hboxlayout7.addWidget(self.lowerOutStepperUnits)
        self.gridlayout2.addLayout(self.hboxlayout7, 2, 0, 1, 1)
        self.hboxlayout8 = QtGui.QHBoxLayout()
        self.hboxlayout8.setSpacing(1)
        self.hboxlayout8.setObjectName("hboxlayout8")
        self.lowerMoveAbs = QtGui.QPushButton(self.lowerStepper)
        self.lowerMoveAbs.setObjectName("lowerMoveAbs")
        self.hboxlayout8.addWidget(self.lowerMoveAbs)
        self.lowerAbsValue = QtGui.QDoubleSpinBox(self.lowerStepper)
        self.lowerAbsValue.setDecimals(3)
        self.lowerAbsValue.setMaximum(20.0)
        self.lowerAbsValue.setSingleStep(0.001)
        self.lowerAbsValue.setProperty("value", QtCore.QVariant(1.0))
        self.lowerAbsValue.setObjectName("lowerAbsValue")
        self.hboxlayout8.addWidget(self.lowerAbsValue)
        self.lowerAbsStepperUnits = widget.TauConfigLabel(self.lowerStepper)
        self.lowerAbsStepperUnits.setMinimumSize(QtCore.QSize(35, 24))
        self.lowerAbsStepperUnits.setMaximumSize(QtCore.QSize(35, 24))
        self.lowerAbsStepperUnits.setProperty("useParentModel", QtCore.QVariant(True))
        self.lowerAbsStepperUnits.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Position?configuration=unit", None, QtGui.QApplication.UnicodeUTF8)))
        self.lowerAbsStepperUnits.setObjectName("lowerAbsStepperUnits")
        self.hboxlayout8.addWidget(self.lowerAbsStepperUnits)
        self.gridlayout2.addLayout(self.hboxlayout8, 3, 0, 1, 1)
        self.vboxlayout1.addWidget(self.lowerStepper)
        self.lowerEnc = widget.TauGroupBox(self.lowerJaw)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowerEnc.sizePolicy().hasHeightForWidth())
        self.lowerEnc.setSizePolicy(sizePolicy)
        self.lowerEnc.setFlat(True)
        self.lowerEnc.setProperty("showText", QtCore.QVariant(False))
        self.lowerEnc.setObjectName("lowerEnc")
        self.gridlayout3 = QtGui.QGridLayout(self.lowerEnc)
        self.gridlayout3.setMargin(0)
        self.gridlayout3.setHorizontalSpacing(4)
        self.gridlayout3.setVerticalSpacing(0)
        self.gridlayout3.setObjectName("gridlayout3")
        self.hboxlayout9 = QtGui.QHBoxLayout()
        self.hboxlayout9.setObjectName("hboxlayout9")
        self.lowerEncLabel = QtGui.QLabel(self.lowerEnc)
        self.lowerEncLabel.setObjectName("lowerEncLabel")
        self.hboxlayout9.addWidget(self.lowerEncLabel)
        self.lowerEncRead = widget.TauValueLabel(self.lowerEnc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowerEncRead.sizePolicy().hasHeightForWidth())
        self.lowerEncRead.setSizePolicy(sizePolicy)
        self.lowerEncRead.setProperty("useParentModel", QtCore.QVariant(True))
        self.lowerEncRead.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Position", None, QtGui.QApplication.UnicodeUTF8)))
        self.lowerEncRead.setObjectName("lowerEncRead")
        self.hboxlayout9.addWidget(self.lowerEncRead)
        self.lowerEncUnits = widget.TauConfigLabel(self.lowerEnc)
        self.lowerEncUnits.setMinimumSize(QtCore.QSize(35, 24))
        self.lowerEncUnits.setMaximumSize(QtCore.QSize(35, 24))
        self.lowerEncUnits.setProperty("useParentModel", QtCore.QVariant(True))
        self.lowerEncUnits.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Position?configuration=unit", None, QtGui.QApplication.UnicodeUTF8)))
        self.lowerEncUnits.setObjectName("lowerEncUnits")
        self.hboxlayout9.addWidget(self.lowerEncUnits)
        self.gridlayout3.addLayout(self.hboxlayout9, 0, 0, 1, 1)
        self.vboxlayout1.addWidget(self.lowerEnc)
        self.offsetLabel = QtGui.QLabel(SCRV)
        self.offsetLabel.setGeometry(QtCore.QRect(20, 370, 88, 40))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.offsetLabel.setFont(font)
        self.offsetLabel.setObjectName("offsetLabel")
        self.gapLabel = QtGui.QLabel(SCRV)
        self.gapLabel.setGeometry(QtCore.QRect(20, 310, 88, 40))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.gapLabel.setFont(font)
        self.gapLabel.setObjectName("gapLabel")
        self.gapAndOffset = QtGui.QGroupBox(SCRV)
        self.gapAndOffset.setGeometry(QtCore.QRect(120, 300, 131, 128))
        self.gapAndOffset.setFlat(True)
        self.gapAndOffset.setObjectName("gapAndOffset")
        self.vboxlayout2 = QtGui.QVBoxLayout(self.gapAndOffset)
        self.vboxlayout2.setSpacing(0)
        self.vboxlayout2.setMargin(0)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.gap = widget.TauGroupBox(self.gapAndOffset)
        self.gap.setProperty("showText", QtCore.QVariant(False))
        self.gap.setObjectName("gap")
        self.vboxlayout3 = QtGui.QVBoxLayout(self.gap)
        self.vboxlayout3.setMargin(0)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.hboxlayout10 = QtGui.QHBoxLayout()
        self.hboxlayout10.setObjectName("hboxlayout10")
        self.gapRead = widget.TauValueLabel(self.gap)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gapRead.sizePolicy().hasHeightForWidth())
        self.gapRead.setSizePolicy(sizePolicy)
        self.gapRead.setProperty("useParentModel", QtCore.QVariant(True))
        self.gapRead.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Position", None, QtGui.QApplication.UnicodeUTF8)))
        self.gapRead.setObjectName("gapRead")
        self.hboxlayout10.addWidget(self.gapRead)
        self.gapReadUnits = widget.TauConfigLabel(self.gap)
        self.gapReadUnits.setMinimumSize(QtCore.QSize(35, 24))
        self.gapReadUnits.setMaximumSize(QtCore.QSize(35, 24))
        self.gapReadUnits.setProperty("useParentModel", QtCore.QVariant(True))
        self.gapReadUnits.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Position?configuration=unit", None, QtGui.QApplication.UnicodeUTF8)))
        self.gapReadUnits.setObjectName("gapReadUnits")
        self.hboxlayout10.addWidget(self.gapReadUnits)
        self.vboxlayout3.addLayout(self.hboxlayout10)
        self.hboxlayout11 = QtGui.QHBoxLayout()
        self.hboxlayout11.setSpacing(4)
        self.hboxlayout11.setObjectName("hboxlayout11")
        self.gapWrite = widget.TauValueLineEdit(self.gap)
        self.gapWrite.setProperty("useParentModel", QtCore.QVariant(True))
        self.gapWrite.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Position", None, QtGui.QApplication.UnicodeUTF8)))
        self.gapWrite.setObjectName("gapWrite")
        self.hboxlayout11.addWidget(self.gapWrite)
        self.gapWriteUnits = widget.TauConfigLabel(self.gap)
        self.gapWriteUnits.setMinimumSize(QtCore.QSize(35, 24))
        self.gapWriteUnits.setMaximumSize(QtCore.QSize(35, 24))
        self.gapWriteUnits.setProperty("useParentModel", QtCore.QVariant(True))
        self.gapWriteUnits.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Position?configuration=unit", None, QtGui.QApplication.UnicodeUTF8)))
        self.gapWriteUnits.setObjectName("gapWriteUnits")
        self.hboxlayout11.addWidget(self.gapWriteUnits)
        self.vboxlayout3.addLayout(self.hboxlayout11)
        self.vboxlayout2.addWidget(self.gap)
        self.offset = widget.TauGroupBox(self.gapAndOffset)
        self.offset.setProperty("showText", QtCore.QVariant(False))
        self.offset.setObjectName("offset")
        self.vboxlayout4 = QtGui.QVBoxLayout(self.offset)
        self.vboxlayout4.setMargin(0)
        self.vboxlayout4.setObjectName("vboxlayout4")
        self.hboxlayout12 = QtGui.QHBoxLayout()
        self.hboxlayout12.setObjectName("hboxlayout12")
        self.offsetRead = widget.TauValueLabel(self.offset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offsetRead.sizePolicy().hasHeightForWidth())
        self.offsetRead.setSizePolicy(sizePolicy)
        self.offsetRead.setProperty("useParentModel", QtCore.QVariant(True))
        self.offsetRead.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Position", None, QtGui.QApplication.UnicodeUTF8)))
        self.offsetRead.setObjectName("offsetRead")
        self.hboxlayout12.addWidget(self.offsetRead)
        self.offsetReadUnits = widget.TauConfigLabel(self.offset)
        self.offsetReadUnits.setMinimumSize(QtCore.QSize(35, 24))
        self.offsetReadUnits.setMaximumSize(QtCore.QSize(35, 24))
        self.offsetReadUnits.setProperty("useParentModel", QtCore.QVariant(True))
        self.offsetReadUnits.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Position?configuration=unit", None, QtGui.QApplication.UnicodeUTF8)))
        self.offsetReadUnits.setObjectName("offsetReadUnits")
        self.hboxlayout12.addWidget(self.offsetReadUnits)
        self.vboxlayout4.addLayout(self.hboxlayout12)
        self.hboxlayout13 = QtGui.QHBoxLayout()
        self.hboxlayout13.setObjectName("hboxlayout13")
        self.OffsetWrite = widget.TauValueLineEdit(self.offset)
        self.OffsetWrite.setProperty("useParentModel", QtCore.QVariant(True))
        self.OffsetWrite.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Position", None, QtGui.QApplication.UnicodeUTF8)))
        self.OffsetWrite.setObjectName("OffsetWrite")
        self.hboxlayout13.addWidget(self.OffsetWrite)
        self.offsetWriteUnits = widget.TauConfigLabel(self.offset)
        self.offsetWriteUnits.setMinimumSize(QtCore.QSize(35, 24))
        self.offsetWriteUnits.setMaximumSize(QtCore.QSize(35, 24))
        self.offsetWriteUnits.setProperty("useParentModel", QtCore.QVariant(True))
        self.offsetWriteUnits.setProperty("model", QtCore.QVariant(QtGui.QApplication.translate("SCRV", "/Position?configuration=unit", None, QtGui.QApplication.UnicodeUTF8)))
        self.offsetWriteUnits.setObjectName("offsetWriteUnits")
        self.hboxlayout13.addWidget(self.offsetWriteUnits)
        self.vboxlayout4.addLayout(self.hboxlayout13)
        self.vboxlayout2.addWidget(self.offset)

        self.retranslateUi(SCRV)
        QtCore.QMetaObject.connectSlotsByName(SCRV)

    def retranslateUi(self, SCRV):
        SCRV.setWindowTitle(QtGui.QApplication.translate("SCRV", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.SCRVName.setText(QtGui.QApplication.translate("SCRV", "SCRVName", None, QtGui.QApplication.UnicodeUTF8))
        self.upperJawLabel.setText(QtGui.QApplication.translate("SCRV", "Upper Jaw", None, QtGui.QApplication.UnicodeUTF8))
        self.lowerJawLabel.setText(QtGui.QApplication.translate("SCRV", "Lower Jaw", None, QtGui.QApplication.UnicodeUTF8))
        self.abort.setText(QtGui.QApplication.translate("SCRV", "Abort", None, QtGui.QApplication.UnicodeUTF8))
        self.upperLimitLabel.setText(QtGui.QApplication.translate("SCRV", "- lim +", None, QtGui.QApplication.UnicodeUTF8))
        self.upperMoveIn.setText(QtGui.QApplication.translate("SCRV", "Move IN", None, QtGui.QApplication.UnicodeUTF8))
        self.upperMoveOut.setText(QtGui.QApplication.translate("SCRV", "Move OUT", None, QtGui.QApplication.UnicodeUTF8))
        self.upperMoveAbs.setText(QtGui.QApplication.translate("SCRV", "Move TO", None, QtGui.QApplication.UnicodeUTF8))
        self.upperEncLabel.setText(QtGui.QApplication.translate("SCRV", "Encoder read:", None, QtGui.QApplication.UnicodeUTF8))
        self.lowerLimitLabel.setText(QtGui.QApplication.translate("SCRV", "- lim +", None, QtGui.QApplication.UnicodeUTF8))
        self.lowerMoveIn.setText(QtGui.QApplication.translate("SCRV", "Move IN", None, QtGui.QApplication.UnicodeUTF8))
        self.lowerMoveOut.setText(QtGui.QApplication.translate("SCRV", "Move OUT", None, QtGui.QApplication.UnicodeUTF8))
        self.lowerMoveAbs.setText(QtGui.QApplication.translate("SCRV", "Move TO", None, QtGui.QApplication.UnicodeUTF8))
        self.lowerEncLabel.setText(QtGui.QApplication.translate("SCRV", "Encoder read:", None, QtGui.QApplication.UnicodeUTF8))
        self.offsetLabel.setText(QtGui.QApplication.translate("SCRV", "Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.gapLabel.setText(QtGui.QApplication.translate("SCRV", "Gap", None, QtGui.QApplication.UnicodeUTF8))

from tau import widget
import scrapers_rc
